language: ruby
rvm:
- 2.3.1
env:
- DB=postgresql
script:
- bundle exec rspec
before_script:
- rails db:create RAILS_ENV=test
- rails db:migrate
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  app: dive-books-camp
  api_key:
    secure: S1tAUqicks21Egjn+qSCCytYF7iF74fxT2beM7wavUNNbloPlo3j57JnoTahceTj+TUV5vxoFonBYTlKRqwJAvGIVoEVhlxtNj9SVkAcIKZyWAz5c0tYF8if+M40L8bTV1COpgm0MDhYDR+l3RHJ81CyS83ANQMrpM/+q9PiUxXjQMutRYv+S9KlqsIPNMj7+TfDcFXxogt5lTgg7BfFRvC9eascDyoa6YPul35d5Sv0+IcoDDcWKztlGEzOH/Mhz99ictyhhdkKt7Z59oBOEtP8/+tQ+Wjv79If/IyXN+1EeiAK2/tfOT37quMtGYufOH27OtQK+S0NFMBt0y6NTX60tO9S2masE87oCw/5ZC4tDQUZchcm0VAw9lCDWUkl3I8V8SS4Fokm4gVIz/vHKhyl7mxCxM8cDirXsfksyF+SoTy3UhRieJ4iDIVoPY/fJ7xLNEzZF8JWMEVl9RzzRKIdEEK76ccg8hCAMEn4oMJDYEjUGPJfTSAl1q4HJiDvPNrlc78rzQT4gcJgKPxUod7s115rLteEuaNIDcjZGEgg/Q2lsKXOFN0TQe7UNmzNKBVUZxRkAyXvmlnF4cNo1OV/ofo4wQb59uFExUKT3k4DE/34IAQRTDakDJUaWbgBuWxC7mdYbdQjGmAVux5cdmbKDQJQyPy8Kg64gYIEe/0=
notifications:
  slack:
    secure: HJgVLG7Xb/3UdRHVMEobjrYljOLk/QGtzbEwuM520M287/GlgO5cwSNves1yvVzWi49xORylVtlBelUdF0A9zic/Sz1ugqX7VzZT9TV438o3CTnrgndv3j6mS/Mq+IR38/uwgC6ohAzV2uB995OEeuOI+3jYRmQmQ8JJz1aboLvqar9uPBWw0AyppFr3dXpoU8IZFEQNu85RF0LGA7Ur9SCZezaLvaGHVd7LYLbjVEREWgL+AD8CAiQxNx3ZGYNepBSRd/Ob7e2aOQR/84qg1pvdAxIbcPah9G0CpkNibhm/hjrjCI+XNztZ7H9nYU7VzUY6C5P7dfJs5xTaFl4/10FmD5hMKLrFjxh+9wVLySFdOudiqPQe4njzCQys2/0ZQM3SrdA7QIk8n5Vgfq5DDkxL081aDjvvWCYncToDueuDt57KlOxv75KSuCtMUXQKd8WPdnGDomN79Tt/BJzGs0tujhWopN3TeT0VzL7XCzy32bFPZO1JLYgKy2Q0R5vui6tQ7EU3Tr1xTqh8sBG0PWbEQy/4J4PdiPfxsDncv0VNBheYyYtMiAV6DgUMn1ZgHkOv8pKE9iRD84dJ9O/rRTBJQtypK+xCzdwR8DDWGlXyNxtetQjf8asW40fec5/Xh7c4e/dxJbRY0Nh9f+10KXC9jxhjC5TCBnem70M1fr4=
